### ISSUE TITLE
When calling "screenshot" from loadFinished callback, no screenshot is made

### ISSUE THREAD

**Issue by paulrutter** [johntitus/node-horseman#52]
When i'm trying to make a screenshot in the callback of "loadFinished", the screenshot is nowhere to be found. No error occurs (success callback, "done" is printed).

When i'm using "screenshot" as a separate callback in the chain, it does work, but the screenshot might not be complete because the page is not done loading.

```javascript
  var horseman = new Horseman();
  horseman
  .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0")
  .viewport(1280, 1024)
  .on("loadFinished", function() {
    horseman.screenshot(path.resolve(__dirname, '123.png')).then(function(){
      console.log("done");
    }, function(e){
      console.error(e);
    });
  })
  .on("error", function(e) {
    console.log("error", e);
  })
  .on("timeout", function(e) {
    console.log("timeout", e);
  })
  .open("http://google.com")
  .finally(function() {
     horseman.close();
  });
```

Am i doing something wrong here?

My environment:
Windows 8
Nodejs 4.1.1
PhantomJS 2.0.0

**Comment by johntitus** [comment]
@paulrutter, can you try this with the new version of horseman I just released (2.2.0)?  I noticed and fixed a possible bug in `screenshot` that might have been causing this.

```js
var Horseman = require('./lib/index');
var path = require('path');

var horseman = new Horseman();
horseman
  .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0")
  .viewport(1280, 1024)
  .open("http://google.com")
  .screenshot(path.resolve(__dirname, '123.png'))
  .finally(function() {
     horseman.close();
  });
```

**Comment by paulrutter** [comment]
@johntitus Thanks for your response. 
Yes, with your code the screenshot is shown, but with my code (with the screenshot call in the loadFinished callback) it's still not working. No errors whatsoever.

**Comment by johntitus** [comment]
Not sure why you're not getting any errors. You're `close`ing the horseman before the screenshot is done rendering. For me, it threw an error saying Phantom was closed.  Why do you want to use the `loadFinished` to take the screenshot?  The `open` method won't finish until the page has fully rendered, so the previous code I posted should work for you.

However, if you really want to do it this way, try this:
```js
var horseman = new Horseman();

horseman
	.userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0")
	.viewport(1280, 1024)
	.on("loadFinished", function() {
		horseman
			.screenshot(path.resolve(__dirname, '123.png'))
			.finally(function(){
				horseman.close();
			})
	})
	.on("error", function(e) {
		console.log("error", e);
	})
	.on("timeout", function(e) {
		console.log("timeout", e);
	})
	.open("http://google.com")
```

**Comment by paulrutter** [comment]
Ah thanks, that did the trick :)
Still, no errors occur when closing Phantom early, but maybe that has something to do with running on Windows?
I will try it in Linux (Docker container) soon.
